apiVersion: v1
kind: Pod
metadata:
  name: build-pod
spec:
  containers:
  - name: kaniko-container
    image: gcr.io/kaniko-project/executor:latest
    args:
    - --context=git://github.com/ri-bhatta/dockerize.git
    - --dockerfile=/Dockerfile
    - --destination=6294720479/myapp:latest
    - --skip-tls-verify
  restartPolicy: Never
  volumes:
  - name: kaniko-secret
    secret:
      secretName: dockerhub-creds
